services:
  api:
    image: palindrome:v0
    restart: always
    ports:
      - "8000:8000"
    user: "1000:1000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/detections
    volumes:
      - .:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: detections
    ports:
      - "5432:5432"
    user: "1000:1000"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
