services:
  test-db:
    container_name: test-db
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=detections
      - TZ=Etc/UTC
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local