services:
  palindrome-api:
    container_name: palindrome-api
    image: palindrome:v0.1
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    user: "1000:1000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - TZ=Etc/UTC

  db:
    container_name: db
    image: postgres:15
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Etc/UTC
    user: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s

volumes:
  postgres_data:
